### ISSUE TITLE
Unifying Newton's Methods

### ISSUE THREAD

**Issue by JaredCrean2** [OptimalDesignLab/PDESolver.jl#11]
The current implementation requires writing a new version of Newton's method for every method of calculating the Jacobian.  This is wasteful and error-prone.  We should have a single Newton's method that dispatches to different methods of calculating the Jacobian based on the options dictionary.

**Comment by jehicken** [comment]
Newton's method should be written so that it is virtually agnostic to the problem being solved.  In theory, it could be a Package outside of PDESolver.jl, although, I suspect this would complicate the introduction of some options.

Actually, you may want to investigate Petsc further.  It may have some nonlinear solvers built-in now.
